### ISSUE TITLE
autodownload screenshots from colab

### ISSUE THREAD

**Issue by jasmine-schoch** [VirtualBrainLab/UnityNeuroscience#128]
where is the "local path" if colab is not saving anywhere? -- does location need to be modified for running off colab?

**Comment by dbirman** [comment]
https://stackoverflow.com/questions/49394737/exporting-data-from-google-colab-to-local-machine

Looks like you can do:
```
from google.colab import files
files.download('filename.csv')
```

You can add a check to the screenshot code that does this automatically if you want, I already have a function that checks whether or not you are in a colab notebook in the `client.py` file

**Comment by jasmine-schoch** [comment]
found within colab ui

**Comment by jasmine-schoch** [comment]
[d636cdd](https://github.com/VirtualBrainLab/Urchin/commit/d636cdd6547deb65eaba0d766a527cc016eb6310)
