### ISSUE TITLE
Callback indices 

### ISSUE THREAD

**Issue by arjunsridhar12345** [VirtualBrainLab/UnityNeuroscience#170]
How does the index get assigned to the points for the callback? When clicking on a point, I would like to map it to a list of some metadata with the assumption that the point I clicked on can be used directly as the index. Is this possible, and do the indices reset when the meshes are cleared? Thanks!

**Comment by dbirman** [comment]
I assume you're referring to the callback feature in this tutorial: https://virtualbrainlab.org/urchin/tutorials/urchin-examples/basics/neurons_meshes.html. 

By default the points get assigned an ID value, which is just the count of points created so far. You can access it from:

```
points = urchin.meshes.Create(1)
points[0].ID
```

You should get that value back through the callback when you click a neuron in the scene.

Let me know if that works for you?

**Comment by arjunsridhar12345** [comment]
yes, this works great. thanks!
