### ISSUE TITLE
Probe position/rotations seem to be getting set wrong in v0.7

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/UnityNeuroscience#190]
Noticed that position is defaulting to world (0,0,0) instead of CCF (0,0,0). Maybe reference coordinate isn't getting set?

Also rotation is now the Pinpoint default rotation but the angles seem to be incorrect because of that...

**Comment by nancymackenzie** [comment]
Is there any update on this, Dan? I'm trying to visualize the Steinmetz lab probes in urchin, and not getting expected positions.

**Comment by dbirman** [comment]
As a temporary solution can you try setting the pip package version to 0.5.3 and using the matching website version https://data.virtualbrainlab.org/Urchin_0_5_3/? 

I know what the issue is so this is a quick fix, just haven't gotten to it.

**Comment by dbirman** [comment]
@nancymackenzie Sorry this took so long, now fixed in ce803c018be743c0a7cf84c8d9cda60ded32dc79

New version of Urchin will be rolled out tonight
