### ISSUE TITLE
Build a BWM visualization example showing each probe insertion colored by lab

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/UnityNeuroscience#37]
Use the data in this CSV file: https://github.com/int-brain-lab/ibl-viz/blob/main/bwm/bwm_all_traj.csv

You'll want to make the root brain area visible and transparent, using the transparent-unlit material and an alpha of ~0.15 (use `set_brain_area_visibility` I think? Take a look at the examples, a lot of them use the 'root' brain area).

After that you need the position and angle of probes. You'll need to call [create_probes ](https://virtualbrainlab.org/_autosummary/unityneuro.render.html#unityneuro.render.set_probe_positions) and then [set_probe_positions ](https://virtualbrainlab.org/_autosummary/unityneuro.render.html#unityneuro.render.set_probe_positions) and [set_probe_angles ](https://virtualbrainlab.org/_autosummary/unityneuro.render.html#unityneuro.render.set_probe_positions) to get this all to work. 

For the probe tip coordinate use the `ml_t_e`, `ap_t_e`, and `dv_t_e` coordinates (the **t** stands for "tip" i.e. the coordinate where the probe tip was placed, the **e** stands for "ephys-aligned histology" which indicates that this coordinate comes from the mouse brain after histology, i.e. this is the "real" coordinate in CCF space). To set the angles use `phi_e` and `theta_e`. 

Then pick a few random colors and use the [set_probe_colors ](https://github.com/VirtualBrainLab/UnityNeuroscience/issues/37) function to set the probe colors according to the lab column.

**Comment by dbirman** [comment]
https://support.apple.com/en-us/HT208721

**Comment by qiqiliang** [comment]
Added probes to grey transparent brain

**Comment by qiqiliang** [comment]
1.) Color probes based on lab column 
2.) Make probes flash, still working on  making probes appear and disappear based on lab

**Comment by qiqiliang** [comment]
Probes change color based on lab every 10 seconds. (All probes for one lab show up and probes from other labs are transparent). A little glitchy

**Comment by dbirman** [comment]
Add a legend, instead of using the short versions of the lab names that are in the CSV file, can you make them a bit more human readable. E.g. instead of steinmetzlab put "Steinmetz Lab (U of Washington)", etc. You can find the lab locations on this page by finding the corresponding PIs https://www.internationalbrainlab.com/our-team#general-assembly

**Comment by qiqiliang** [comment]
Added legend- name of lab appears with probes
