### ISSUE TITLE
Change window size or zoom of additional cameras

### ISSUE THREAD

**Issue by jasmine-schoch** [VirtualBrainLab/UnityNeuroscience#84]
Current window size of cameras cuts off part of the brain

**Comment by jasmine-schoch** [comment]
just need to figure out a better default, and then should be okay?

**Comment by dbirman** [comment]
What's the deal with this issue, is it still open? @jasmine-schoch

**Comment by jasmine-schoch** [comment]
I never changed the default size, but assuming people will be automatically changing the viewing, it should no longer be a problem. @dbirman
