### ISSUE TITLE
Screenshot vanished from camera example script

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/UnityNeuroscience#97]

**Comment by jasmine-schoch** [comment]
[ab509907cb706581ece9add00feec859fb3c826f
](https://github.com/VirtualBrainLab/Urchin/issues/97#issuecomment-1712220997)
Was there other code missing or does this fix it?

**Comment by jasmine-schoch** [comment]
ab509907cb706581ece9add00feec859fb3c826f

**Comment by dbirman** [comment]
I assume you meant to link here? https://github.com/VirtualBrainLab/urchin-examples/commit/ab509907cb706581ece9add00feec859fb3c826f

Yes this is fine, although the whole tutorial needs some instructions added at some point
